-- The original CREATE TABLE statements put the CONSTRAINT name in front of
-- NOT NULL UNIQUE, so PostgreSQL bound each name to the NOT NULL clause and
-- autogenerated <table>_<column>_key for the UNIQUE constraint. This changeset
-- gives the three UNIQUE constraints the uq_ prefix required by the standard.
ALTER TABLE professional_management.specialties
    RENAME CONSTRAINT specialties_name_key TO uq_specialties_name;

ALTER TABLE professional_management.professionals
    RENAME CONSTRAINT professionals_identity_user_id_key TO uq_professionals_identity_user_id;

ALTER TABLE professional_management.professionals
    RENAME CONSTRAINT professionals_license_number_key TO uq_professionals_license_number;
